### ISSUE TITLE
UTF-8 encoded files are not loaded properly

### ISSUE THREAD

**Issue by aleksandarkovacevic30** [evshvarov/csvgen#10]
If I try to load the following file:

https://raw.githubusercontent.com/zauberware/postal-codes-json-xml-csv/master/data/AT/zipcodes.at.csv

It loads all the characters like üöäß wrongly.

**Comment by evshvarov** [comment]
What's your local in IRIS?

**Comment by aleksandarkovacevic30** [comment]
Locale properties of enuw (English, United States, Unicode):  
Your current locale is: enuw (English, United States, Unicode)
--
(enuw is a system locale. Edit is not allowed.)

**Comment by evshvarov** [comment]
<img width="896" alt="Screenshot 2021-12-22 at 17 06 28" src="https://user-images.githubusercontent.com/2781759/147105313-ca2b2d41-336d-4e3b-ba84-a06faaad5924.png">
Looks good to me. Is it wrong here?
