### ISSUE TITLE
Doesn't work on Windows?

### ISSUE THREAD

**Issue by isc-bspead** [evshvarov/csvgen#13]
I used zpm to pull down the latest release and when I tried to import a csv from my local drive it failed because it was using the ":" in the classname:

`USER>s sc=##class(community.csvgen).Generate("C:\temp\badge\oxford.csv")         
USER>w $system.Status.GetErrorText(sc)
ERROR #5540: SQLCODE: -400 Message: ERROR #5794: Datatype validation failed on type '%Dictionary.Classname', with value equal to "community.csvgen.generated.C:te20211208"
  > ERROR #5802: Datatype validation failed on property '%Dictionary.ClassDefinition:Name', with value equal to "community.csvgen.generated.C:te20211208"`

If I specify the table name it will proceed past this point (although it fails later on on data import and I haven't gotten to the bottom of that yet)

**Comment by evshvarov** [comment]
Hi Ben!
Great catch!
I'd appreciate if you introduce a PR!
