### ISSUE TITLE
Execution error (if is wrong)

### ISSUE THREAD

**Issue by yurimarx** [evshvarov/csvgen#15]
https://github.com/evshvarov/csvgen/blob/49cb5b6ab60902ef039c20181cb3efca374326c2/src/community/csvgen.cls#L27

**Comment by evshvarov** [comment]
It happens only if there was a bug during CSV import.

Ср, 12 янв. 2022 г. в 18:49, Yuri Marx Pereira Gomes <
***@***.***>:

**Comment by evshvarov** [comment]
So the internal generator failed to create an Import method

Ср, 12 янв. 2022 г. в 18:50, Евгений Шваров ***@***.***>:

**Comment by evshvarov** [comment]
@yurimarx - what is the csv that failed? I think it could work in the latest version

**Comment by evshvarov** [comment]
No update, closing
