### ISSUE TITLE
a semicolon separator does not create a class

### ISSUE THREAD

**Issue by SergeyMi37** [evshvarov/csvgen#2]
When importing a csv file with the delimiter ";" class is not generated. The study showed that the parameter delimiter is not passed to the function of the receiving column 

do ##class(%SQL.Util.RowType).parseArray("numer INTEGER;login VARCHAR(250);fio VARCHAR(250);name VARCHAR(250)",.col) 
write
col=3
col(1)="numer"
col(1,1)="INTEGER;login VARCHAR(250)"
col(1,2)="User.INTEGER;login VARCHAR"
col(2)=";fio"
col(2,1)="VARCHAR(250)"
col(2,2)="%Library.String"
col(2,2,"MAXLEN")=250
col(3)=";name"
col(3,1)="VARCHAR(250)"
col(3,2)="%Library.String"
col(3,2,"MAXLEN")=250

**Comment by SergeyMi37** [comment]
parsing generates invalid field names

**Comment by evshvarov** [comment]
FIxed with version 1.1.5
