### ISSUE TITLE
Add the translation table pTranslateTable to the Generate method

### ISSUE THREAD

**Issue by SergeyMi37** [evshvarov/csvgen#3]

**Comment by evshvarov** [comment]
Do you mean to convert the source data while importing to IRIS?

**Comment by SergeyMi37** [comment]
Yes, i can do it myself

**Comment by evshvarov** [comment]
or make a pull request?

**Comment by SergeyMi37** [comment]
yes, I can do a PR. This is urgent ?

**Comment by evshvarov** [comment]
Not at all.

вс, 24 янв. 2021 г. в 09:35, Sergey Mikhaylenko <notifications@github.com>:

**Comment by SergeyMi37** [comment]
Need to modify class% SQL.Util.Procedures

**Comment by SergeyMi37** [comment]
there the translation table is used only for defining field names, and is not used during import
