### ISSUE TITLE
When Use a csv with only 0/1 in column values I get error

### ISSUE THREAD

**Issue by renatobanzai** [evshvarov/csvgen#4]
My csv example:

Col1,Col2
0,1
1,0

> d ##class(community.csvgen).Generate("/irisdev/app/test_banzai7.csv",",","test.matriz2")
>                 do ##class(community.datatypes).Guess($Piece(line(r),dlm,i),.types)
> <UNDEFINED>zGetRowTypes+20^community.csvgen.1 *line(1)

I tried to use the prowtype but I actually dont know how

**Comment by evshvarov** [comment]
@renatobanzai - could you please share the sample file?

**Comment by evshvarov** [comment]
@renatobanzai - nevermind, see it ) sorry )

**Comment by renatobanzai** [comment]
All working! Thanks!
