### ISSUE TITLE
This utility doesn't work on Windows

### ISSUE THREAD

**Issue by asinay** [evshvarov/csvgen#6]
I tried to run this utility on a Windows machine and got the following error:

**SAMPLESBI>**do ##class(community.csvgen).Generate("C:\temp\CSV\SurveysResults.csv")
 
**SAMPLESBI>**w
 
%objlasterror="0 K¤ä Host variable name must begin with either % or a letter, not '\'^SELECT COUNT(1) as "result" FROM community_csvgen_generated.C:»
                                                                           SAMPLESBI¬$e^zOnAsStatus+1^%Exception.SQL.1^10e^zAsStatus+1^%Exception.AbstractException.1^1+e^zHowManyRecords+10^community.csvgen.1^1$e^zGenerate+5^community.csvgen.1^1d^^^0"
%sqlcontext=<OBJECT REFERENCE>[1@%Library.ProcedureContext]

**SAMPLESBI>**d $system.OBJ.DisplayError()
 
ERROR #5540: SQLCODE: -28 Message:  Host variable name must begin with either % or a letter, not '\'^SELECT COUNT(1) as "result" FROM community_csvgen_generated.C:

This line in the Community.csvgen class Generate classmethod, doesn't support Windows paths:
_$TR($E(fncsv,1,5),"/.","")_

Thanks,
Asaf

**Comment by evshvarov** [comment]
Thanks, Asaf! Pull request?

вт, 29 сент. 2020 г. в 20:13, Asaf Sinay <notifications@github.com>:

**Comment by evshvarov** [comment]
Fixed with 1.1.8 release. @asinay , please check?

**Comment by evshvarov** [comment]
And could you please try with [csvgen-ui](https://openexchange.intersystems.com/package/csvgen-ui) on Windows?
