### ISSUE TITLE
Option to append files

### ISSUE THREAD

**Issue by yurimarx** [evshvarov/csvgen#9]
I need an option to append files to import using csvgen:

zpm "install csvgen"
    set file="https://github.com/yurimarx/automl-nasdaq/raw/master/datasource/NASDAQ_100_Data_From_2010-1.csv"
    zw ##class(community.csvgen).GenerateFromURL(file,",","dc.automl.nasdaq")
    set file2="https://github.com/yurimarx/automl-nasdaq/raw/master/datasource/NASDAQ_100_Data_From_2010-2.csv"
    zw ##class(community.csvgen).GenerateFromURL(file2,",","dc.automl.nasdaq")
    set file3="https://github.com/yurimarx/automl-nasdaq/raw/master/datasource/NASDAQ_100_Data_From_2010-3.csv"
    zw ##class(community.csvgen).GenerateFromURL(file3,",","dc.automl.nasdaq")

PS: the separator to these files is tab, and not ,

**Comment by evshvarov** [comment]
fair enough. Will implement some day but PR is welcome!
